language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

os:
  - linux
#  - osx

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - coverage run --source="pymdc" -m unittest tests

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
